gestionSSA/aerodromes/urls.py
from django.urls import path
from . import views
from django.contrib import admin 


app_name='aerodromes'

urlpatterns = [
  
    path('', views.home, name='accueil'),
    path('evts/', views.pageevts, name='accueilevts'),
    path('evts/perilanimal', views.afficherperilanimal, name='perilanimal'),
    path('evts/requetesepecif', views.afficherrequetesepecif, name='requetesepecif'),
    path('evts/requetesepecif/resultatrequetespeci', views.afficherresultatrequetespeci, name='resultatrequetespeci'),
    
    path('evts/feunalaser', views.afficherfeunalaser, name='feunalaser'),
    path('psc/', views.afficherpsc, name='psc'),
    path('psc/aibd', views.afficherpscaibd, name='pscaibd'),
    path('psc/slouis', views.afficherpscslouis, name='slouis'),
    path('psc/tamb', views.afficherpsctamb, name='tamb'),
    path('psc/cap', views.afficherpsccap, name='cap'),
    path('psc/zig', views.afficherpsczig, name='zig'),
    path('pscr/', views.afficherpscr, name='pscr'),
    path('pscr/pscrcentre', views.afficherpscrcentre, name='pscrcentre'),
    path('pscr/pscrnord', views.afficherpscrnord, name='pscrnord'),
    path('pscr/pscrest', views.afficherpscrest, name='pscrest'),
    path('pscr/pscrsud', views.afficherpscrsud, name='pscrsud'),
    path('realise/', views.afficherrealise, name='realise'),
    path('aerodromesSenegal/', views.afficheraerodromesSenegal, name='aerodromesSenegal'),
    path('psc/inspectionsdepartement/', views.afficherinspectionsdepartement, name='inspectionsdepartement'),
    path('pscr/inspectionsrdepartement/', views.afficherinspectionsrdepartement, name='inspectionsrdepartement'),
    path('psc/inspectionsdepartement/aibddepart', views.afficherpscaibddepart, name='pscaibddepart'),
    path('psc/inspectionsdepartement/slouisdepart', views.afficherpscslouisdepart, name='pscslouisdepart'),
    path('psc/inspectionsdepartement/tambdepart', views.afficherpsctambdepart, name='psctambdepart'),
    path('psc/inspectionsdepartement/capdepart', views.afficherpsccapdepart, name='psccapdepart'),
    path('psc/inspectionsdepartement/zigdepart', views.afficherpsczigdepart, name='psczigdepart'),
    path('planform/', views.homeplanform, name='accueilplanform'),
    path('planning/', views.afficherplanning, name='planning'),
    path('documentation/', views.afficherdocumentation, name='documentation'),
    path('planning/formationsdepartement/', views.afficherformationsdepartement, name='formationsdepartement'),
    path('realise/dossierinspection', views.afficherdossierinspection, name='dossierinspection'),
    path('formationsrealisees/', views.afficherformationsrealisees, name='formationsrealisees'),
    path('prioriteformations/', views.afficherprioriteformations, name='prioriteformations'),
    path('listeinspecteurs/', views.afficherlisteinspecteurs, name='listeinspecteurs'),  
    
    path('formationsrealisees/dossierformation', views.afficherdossierformation, name='dossierformation'),
    path('listeinspecteurs/dossieragent', views.afficherdossierinspecteur, name='dossieragent'),
    
    path('aerodromesSenegal/dossieraerodrome', views.afficherdossieraerodrome, name='dossieraerodrome'),
    path('evts/dossierevenementsecu', views.afficherdossierevenementsecu, name='dossierevenementsecu'),
    
    
        
    path('admin/', admin.site.urls),   
]

gestionSSA/comptes/urls.py
from django.urls import path
from django.contrib.auth import views


app_name='comptes'

urlpatterns = [
  
    path('login/', views.LoginView.as_view(), name='login'),
    path('logout/', views.LogoutView.as_view(), name='logout'),
    path('password-reset/', views.PasswordResetView.as_view(), name='password_reset'),
	 path('password-reset/done/', views.PasswordResetDoneView.as_view(), name='password_reset_done'),
 	 path('reset/<uidb64>/<token>/', views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
	 path('reset/done/', views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
    path('password-change/', views.PasswordChangeView.as_view(), name='password_change'),
	 path('password-change/done/', views.PasswordChangeDoneView.as_view(), name='password_change_done'),
	 
]

gestionSSA/gestionSSA/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings



urlpatterns = [
	 path('admin/', admin.site.urls),
	 path('comptes/', include('comptes.urls')),
	 path('aerodromes/', include('aerodromes.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) 

gestionSSA/aerodromes/forms.py
from django.forms import ModelForm
from .models import Choixdepartement, Dossierinspection, Dossieraerodrome, Dossierevenementsecu, Dossierformation, Dossieragent, Evtsecurite
from django import forms



class ChoixdepartementForm(ModelForm):
    class Meta:
        model = Choixdepartement
        exclude = ['descript']
        
        
        

class DossierinspectionForm(ModelForm):
	class Meta:
		model = Dossierinspection
		exclude = ['description', 'dossierinsp', 'datedocument' ]
		

class DossieraerodromeForm(ModelForm):
	class Meta:
		model = Dossieraerodrome
		exclude = ['descriptiondossier', 'dossieraero', 'datedoc' ]
		
		

class DossierevenementsecuForm(ModelForm):
	class Meta:
		model = Dossierevenementsecu
		exclude = ['descriptiondocumentevt', 'dossierevt', 'datedocumentevt' ]
		
		
class DossierformationForm(ModelForm):
	class Meta:
		model = Dossierformation
		exclude = ['description', 'dossierformation', 'datedocument' ]
		
		
		
class DossieragentForm(ModelForm):
	class Meta:
		model = Dossieragent
		exclude = ['descriptiondocumentagent', 'dossieragent', 'datedocumentagent' ]
		
		

class EvtsecuriteForm(ModelForm):
	
	choixaero = forms.BooleanField(initial=False, required=False)
	choixdebut = forms.DateField(required=False)
	choixfin = forms.DateField(required=False)
	choixperiode = forms.BooleanField(initial=False, required=False)
	
	
	class Meta:
		model = Evtsecurite
		exclude = ['latitudeevt', 'longitudeevt', 'dateevt', 'heureevt', 'notifiantevt', 'immataeronefevt', 
		'descripinsp', 'notifevt', 'nomanimalevt', 'statutevt', 'lieuevt', 'classeevt', 'groupeanimalevt']
		
		

"""class ChoixrequeteForm(forms.Form):
	choixclassevt = forms.BooleanField(required=False)
	choixgrpanim = forms.BooleanField(required=False)
	choixaero = forms.BooleanField(required=False)
	choixdebut = forms.DateField(required=False)
	choixfin = forms.DateField(required=False)
	choixperiode = forms.BooleanField(required=False)"""
	   

   

gestionSSA/aerodromes/views.py
from django.shortcuts import render,redirect
from django.contrib.auth.decorators import login_required
from .models import Inspection, Aerodrome
import collections

from django.http import HttpResponse, Http404
from datetime import datetime, timedelta

from .models import Agentac, Formationac, DomaineInspection, Dossierinspection, Dossieraerodrome, Evtsecurite, Dossierevenementsecu, Dossierformation, Dossieragent, Document
from django.views import generic
from django.contrib.auth.decorators import login_required

from .forms import ChoixdepartementForm, DossierinspectionForm, DossieraerodromeForm, DossierevenementsecuForm, DossierformationForm, DossieragentForm, EvtsecuriteForm
from django.db.models import Q



@login_required
def home(request):
	
	aeroportinternationaux = Aerodrome.objects.filter(Q(aerointernational=True))
	aeroportnationaux = Aerodrome.objects.filter(Q(aerointernational=False))
	
	return render(request, 'aerodromes/accueil.html', {
	'aeroportinternationaux': aeroportinternationaux,
	'aeroportnationaux': aeroportnationaux,
	
	 })


@login_required
def pageevts(request):
	evenementssecurite = Evtsecurite.objects.all()
	tauxevtsPAN = 0
	tauxevtsFDG = 0
	tauxevtsMET = 0
	tauxevtsAUT = 0
	
	nbreevtsecu = Evtsecurite.objects.all().count()
	nbreevtsPAN = Evtsecurite.objects.filter(Q(typeevt='PAN')).count()
	nbreevtsFDG = Evtsecurite.objects.filter(Q(typeevt='FDG')).count()
	nbreevtsMET = Evtsecurite.objects.filter(Q(typeevt='MET')).count()
	
	if(nbreevtsecu != 0):
		tauxevtsPAN = round(100*(nbreevtsPAN/nbreevtsecu),2)
		tauxevtsFDG = round(100*(nbreevtsFDG/nbreevtsecu),2)
		tauxevtsMET = round(100*(nbreevtsMET/nbreevtsecu),2)
		tauxevtsAUT = round((100*(nbreevtsecu - nbreevtsPAN - nbreevtsFDG - nbreevtsMET)/nbreevtsecu),2)
	
	form = DossierevenementsecuForm()
	return render(request, 'aerodromes/evenementsSecurite/accueil.html', {
	'evenementssecurite': evenementssecurite,
	'form': form,
	'tauxevtsPAN': tauxevtsPAN,
	'tauxevtsFDG': tauxevtsFDG,
	'tauxevtsMET': tauxevtsMET,
	'tauxevtsAUT': tauxevtsAUT,
	
	})
    



@login_required
def afficherperilanimal(request):
    """ Exemple de page non valide au niveau HTML pour que l'exemple soit concis """
    
   
    anneecourante = datetime.today().year
         
    evtsecuanneecourante = Evtsecurite.objects.filter(Q(dateevt__year = anneecourante), Q(typeevt = 'PAN'))
    evtsecuanneepreceden = Evtsecurite.objects.filter(Q(dateevt__year = anneecourante-1), Q(typeevt = 'PAN'))
    
    nbreevtsecuanneecourante = evtsecuanneecourante.count()
    nbreevtsecuanneepreceden = evtsecuanneepreceden.count()
        
    formattedtypeevts = [format(evt.dateevt.month) for evt in evtsecuanneecourante]
    formattedtypeevtsp = [format(evt.dateevt.month) for evt in evtsecuanneepreceden]
    
    evtpanancourparmois = {x:formattedtypeevts.count(x) for x in formattedtypeevts}
    lesevtpan = list(evtpanancourparmois.keys())
    nbredevpanparmois = list(evtpanancourparmois.values())
    evtspanmoisnbre = []
    cteur = 0
    for i in lesevtpan:
    	bonformat = {}
    	bonformat['mois'] = lesevtpan[cteur]
    	bonformat['nbreevt'] = nbredevpanparmois[cteur]
    	evtspanmoisnbre.append(bonformat)
    	cteur = cteur + 1
    
    evtspanmoisnbre = sorted(evtspanmoisnbre, key = lambda i: i['mois'])
    
    evtpanancourparmoisp = {x:formattedtypeevtsp.count(x) for x in formattedtypeevtsp}
    lesevtpanp = list(evtpanancourparmoisp.keys())
    nbredevpanparmoisp = list(evtpanancourparmoisp.values())
    evtspanmoisnbrep = []
    cteur = 0
    for i in lesevtpanp:
    	bonformatp = {}
    	bonformatp['mois'] = lesevtpanp[cteur]
    	bonformatp['nbreevt'] = nbredevpanparmoisp[cteur]
    	evtspanmoisnbrep.append(bonformatp)
    	cteur = cteur + 1
    
    evtspanmoisnbrep = sorted(evtspanmoisnbrep, key = lambda i: i['mois'])
    bonnelisteevt = []
    for i in range(12):
    	bonformatbon = {}
    	bonformatbon['mois'] = i+1
    	bonformatbon['nbreevt'] = 0
    	bonnelisteevt.append(bonformatbon)
    	
    bonnelisteevtan = []
    for i in range(12):
    	bonformatbonan = {}
    	bonformatbonan['mois'] = i+1
    	bonformatbonan['nbreevt'] = 0
    	bonnelisteevtan.append(bonformatbonan)
    	
    for ev in evtspanmoisnbre:
    	for i in bonnelisteevtan:
    		if str(ev['mois']) == str(i['mois']):
    			i['nbreevt'] = ev['nbreevt']
    	
    for ev in evtspanmoisnbrep:
    	for i in bonnelisteevt:
    		if str(ev['mois']) == str(i['mois']):
    			i['nbreevt'] = ev['nbreevt']
  	              
    
    return render(request, 'aerodromes/evenementsSecurite/Perilanimalier.html',{
    
    'bonnelisteevt': bonnelisteevt,
    'bonnelisteevtan': bonnelisteevtan,
    'anneecourante': anneecourante,
    'anneeprecedente': anneecourante-1,
    'evtsecuanneecourante': evtsecuanneecourante, 
    'evtsecuanneepreceden': evtsecuanneepreceden,
    'nbreevtsecuanneepreceden': nbreevtsecuanneepreceden,
    'nbreevtsecuanneecourante': nbreevtsecuanneecourante,
    })
    



@login_required
def afficherrequetesepecif(request):
    """ Exemple de page non valide au niveau HTML pour que l'exemple soit concis """
    
    anneecourante = datetime.today().year
    evenementssecurites = Evtsecurite.objects.all()
         
    evtsecuanneecourante = Evtsecurite.objects.filter(Q(dateevt__year = anneecourante))
    evtsecuanneepreceden = Evtsecurite.objects.filter(Q(dateevt__year = anneecourante-1))
    
    nbreevtsecuanneecourante = evtsecuanneecourante.count()
    nbreevtsecuanneepreceden = evtsecuanneepreceden.count()
        
    formattedtypeevts = [format(evt.dateevt.month) for evt in evtsecuanneecourante]
    formattedtypeevtsp = [format(evt.dateevt.month) for evt in evtsecuanneepreceden]
    
    evtpanancourparmois = {x:formattedtypeevts.count(x) for x in formattedtypeevts}
    lesevtpan = list(evtpanancourparmois.keys())
    nbredevpanparmois = list(evtpanancourparmois.values())
    evtspanmoisnbre = []
    cteur = 0
    for i in lesevtpan:
    	bonformat = {}
    	bonformat['mois'] = lesevtpan[cteur]
    	bonformat['nbreevt'] = nbredevpanparmois[cteur]
    	evtspanmoisnbre.append(bonformat)
    	cteur = cteur + 1
    
    evtspanmoisnbre = sorted(evtspanmoisnbre, key = lambda i: i['mois'])
    
    evtpanancourparmoisp = {x:formattedtypeevtsp.count(x) for x in formattedtypeevtsp}
    lesevtpanp = list(evtpanancourparmoisp.keys())
    nbredevpanparmoisp = list(evtpanancourparmoisp.values())
    evtspanmoisnbrep = []
    cteur = 0
    for i in lesevtpanp:
    	bonformatp = {}
    	bonformatp['mois'] = lesevtpanp[cteur]
    	bonformatp['nbreevt'] = nbredevpanparmoisp[cteur]
    	evtspanmoisnbrep.append(bonformatp)
    	cteur = cteur + 1
    
    evtspanmoisnbrep = sorted(evtspanmoisnbrep, key = lambda i: i['mois'])
    bonnelisteevt = []
    for i in range(12):
    	bonformatbon = {}
    	bonformatbon['mois'] = i+1
    	bonformatbon['nbreevt'] = 0
    	bonnelisteevt.append(bonformatbon)
    	
    bonnelisteevtan = []
    for i in range(12):
    	bonformatbonan = {}
    	bonformatbonan['mois'] = i+1
    	bonformatbonan['nbreevt'] = 0
    	bonnelisteevtan.append(bonformatbonan)
    	
    for ev in evtspanmoisnbre:
    	for i in bonnelisteevtan:
    		if str(ev['mois']) == str(i['mois']):
    			i['nbreevt'] = ev['nbreevt']
    	
    for ev in evtspanmoisnbrep:
    	for i in bonnelisteevt:
    		if str(ev['mois']) == str(i['mois']):
    			i['nbreevt'] = ev['nbreevt']
    
   
    
    form = EvtsecuriteForm()	
    
    return render(request, 'aerodromes/evenementsSecurite/requetesepecif.html', {
    'form': form,
    
    'bonnelisteevt': bonnelisteevt,
    'bonnelisteevtan': bonnelisteevtan,
    'anneecourante': anneecourante,
    'anneeprecedente': anneecourante-1,
    'evtsecuanneecourante': evtsecuanneecourante, 
    'evtsecuanneepreceden': evtsecuanneepreceden,
    'nbreevtsecuanneepreceden': nbreevtsecuanneepreceden,
    'nbreevtsecuanneecourante': nbreevtsecuanneecourante,
    'evenementssecurites': evenementssecurites,
    
    })


@login_required
def afficherresultatrequetespeci(request):
	
	if request.method == 'POST':
		aerodevt = '--(TOUS)'
		
		choixdebut = '--'
		choixfin = '-- (à tout moment)'
		form = EvtsecuriteForm(request.POST)
		
		if form.is_valid():
			typedevt = form.cleaned_data['typeevt']
			
			choixaero = form.cleaned_data['choixaero']
			choixperiode = form.cleaned_data['choixperiode']
									
			anneecourante = datetime.today().year
			evenementssecurites = Evtsecurite.objects.filter(Q(typeevt = typedevt))
			
			evtsecuanneecourante = Evtsecurite.objects.filter(Q(dateevt__year = anneecourante), Q(typeevt = typedevt))
			evtsecuanneepreceden = Evtsecurite.objects.filter(Q(dateevt__year = anneecourante-1), Q(typeevt = typedevt))
			
			if choixaero == True:
				aerodevt = form.cleaned_data['nomaero'].nomaero
				evtsecuanneecourante = evtsecuanneecourante.filter(Q(nomaero__nomaero = aerodevt))
				evtsecuanneepreceden = evtsecuanneepreceden.filter(Q(nomaero__nomaero = aerodevt))
			if choixperiode == True:
				choixdebut = form.cleaned_data['choixdebut']
				choixfin = form.cleaned_data['choixfin']
				evenementssecurites = evenementssecurites.filter(Q(dateevt__lte = choixfin), Q(dateevt__gte = choixdebut))
			
			formattedtypeevts = [format(evt.dateevt.month) for evt in evtsecuanneecourante]
			formattedtypeevtsp = [format(evt.dateevt.month) for evt in evtsecuanneepreceden]
			evtpanancourparmois = {x:formattedtypeevts.count(x) for x in formattedtypeevts}
			lesevtpan = list(evtpanancourparmois.keys())
			nbredevpanparmois = list(evtpanancourparmois.values())
			evtspanmoisnbre = []
			cteur = 0
			for i in lesevtpan:
				bonformat = {}
				bonformat['mois'] = lesevtpan[cteur]
				bonformat['nbreevt'] = nbredevpanparmois[cteur]
				evtspanmoisnbre.append(bonformat)
				cteur = cteur + 1
				
			evtspanmoisnbre = sorted(evtspanmoisnbre, key = lambda i: i['mois'])
			evtpanancourparmoisp = {x:formattedtypeevtsp.count(x) for x in formattedtypeevtsp}

gestionSSA/aerodromes/templates/aerodromes/evenementsSecurite/accueil.html
{% extends 'adminlte/base.html' %}
{% load static %}

{% block extra_head %}
	
	
	 <!-- Bootstrap 3.3.7 -->
  <link href="{% static "aerodromes/bower_components/bootstrap/dist/css/bootstrap.min.css" %}" rel="stylesheet" />
  <!-- Font Awesome -->
  <link href="{% static "aerodromes/bower_components/font-awesome/css/font-awesome.min.css" %}" rel="stylesheet"/>
  <!-- Ionicons -->
 <link href="{% static "aerodromes/bower_components/Ionicons/css/ionicons.min.css" %}"  rel="stylesheet"/>
  <!-- DataTables -->
  <link href="{% static "aerodromes/bower_components/datatables.net-bs/css/dataTables.bootstrap.min.css" %}" rel="stylesheet" />
{% endblock %}
{% block title %}ANACIM DNAA{% endblock %}
{% block logo_href %}/{% endblock %}
{% block page_name %}TABLEAU DE BORD{% endblock %}
{% block page_actions %}{% endblock %}
{% block page_description %}{% endblock %}
{% block breadcrumbs %} {% endblock %}


{% block content_wrapper %}
  
  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
      <h1>
        EVENEMENTS DE SECURITE/
        <small>Suivi des Indicateurs</small>
      </h1>
     
    </section>

    <!-- Main content -->
    <section class="content">
      <!-- Small boxes (Stat box) -->
      <div class="row">
        <div class="col-lg-3 col-xs-6">
          <!-- small box -->
          <div class="small-box bg-black">
            <div class="inner">
              <h3>{{tauxevtsPAN}}<sup style="font-size: 20px">%</sup></h3>

              <p>Risque Animalier</p>
            </div>
           
            <a href="{% url 'aerodromes:perilanimal' %}" class="small-box-footer">Plus d'info <i class="fa fa-arrow-circle-right"></i></a>
          </div>
        </div>
        <!-- ./col -->
        <div class="col-lg-3 col-xs-6">
          <!-- small box -->
          <div class="small-box bg-black">
            <div class="inner">
              <h3>{{tauxevtsFDG}}<sup style="font-size: 20px">%</sup></h3>

              <p>Feux Dangereux (laser...)</p>
            </div>
           
            <a href="{% url 'aerodromes:feunalaser' %}" class="small-box-footer">Plus d'info <i class="fa fa-arrow-circle-right"></i></a>
          </div>
        </div>
        <!-- ./col -->
        <div class="col-lg-3 col-xs-6">
          <!-- small box -->
          <div class="small-box bg-black">
            <div class="inner">
              <h3>{{tauxevtsMET}}<sup style="font-size: 20px">%</sup></h3>

              <p>Conditions Météo</p>
            </div>
           
            <a href="{% url 'aerodromes:accueilevts' %}" class="small-box-footer">Plus d'info <i class="fa fa-arrow-circle-right"></i></a>
          </div>
        </div>
        <!-- ./col -->
        <div class="col-lg-3 col-xs-6">
          <!-- small box -->
          <div class="small-box bg-black">
            <div class="inner">
              <h3>{{tauxevtsAUT}}<sup style="font-size: 20px">%</sup></h3>

              <p>Autres</p>
            </div>
            
            <a href="{% url 'aerodromes:accueilevts' %}" class="small-box-footer">Plus d'info <i class="fa fa-arrow-circle-right"></i></a>
          </div>
        </div>
        <!-- ./col -->
      </div>
      
      <div class="row">
        <div class="col-xs-12">
          

          <div class="box">
            <div class="box-header">
              <h3 class="box-title">Evénements de sécurité</h3>
            </div>
            <!-- /.box-header -->
            <div class="box-body table-responsive">
              <table id="example2" class="table table-bordered table-striped">
                <thead>
                <tr>
                  <th>Référence</th>
                  <th>Type</th>
                  <th>Lieu</th>
                  <th>Date Occurrence</th>
                  <th>Heure</th>
                  <th>Notifiant</th>
                  <th>Fiche de Notification</th>
                </tr>
                </thead>
                <tbody>
                {% for evt in evenementssecurite %}
                <tr>
                  <td>{{ evt.codeevt }}</td>
                  <td>{{ evt.typeevt }}</td>
                  <td>{{ evt.lieuevt }}</td>
                  <td>{{ evt.dateevt }}</td>
                  <td>{{ evt.heureevt }}</td>
                  <td>{{ evt.notifiantevt }}</td>
                  <td><a href="{{ evt.notifevt.url }}">Telecharger le fichier</a></td>
                  
                  
                </tr>
                 {% endfor %}       
               
                </tbody>
                <tfoot>
                
                </tfoot>
              </table>
            </div>
            <!-- /.box-body -->
          </div>
          <!-- /.box -->
        </div>
        <!-- /.col -->
      </div>
      <!-- /.row -->
      
            <!-- /.row -->
      <section class="content-header">
      <h1>
        DOSSIER DES EVENEMENTS DE SECURITE /
        <small>Suivi des Evénements de Sécurité</small>
      </h1>
     
    </section>
      <div class="row">
         <div class="col-xs-12">
          

          <div class="box">
           
            <!-- /.box-header -->
            <div class="box-body">
              <form action="{% url 'aerodromes:dossierevenementsecu' %}" method="post">
               <div class="form-group"><p>
                <label><h5>Choisir le code de l'événement de sécurité et valider pour afficher plus d'informations</h5> </label>
                </p>
                <br>
                
                 {% csrf_token %}
                
    				  {{ form }}
    				</div>
                
              <input type="submit" value="Valider">
              </form>  
              
            </div>
            <!-- /.box-body -->
          </div>
          <!-- /.box -->
        </div>
      
       
      </div>
      
    </section>
    <!-- /.content -->
  
  </div>
  <!-- /.content-wrapper -->        
{% endblock %}

{% block extra_foot %}


<!-- jQuery 3 -->
<!-- <script src="{% static "planformations/bower_components/jquery/dist/jquery.min.js" %}"></script>
<!-- Bootstrap 3.3.7 -->
<!-- <script src="{% static "planformations/bower_components/bootstrap/dist/js/bootstrap.min.js" %}"></script>
<!-- DataTables -->
<script src="{% static "aerodromes/bower_components/datatables.net/js/jquery.dataTables.js" %}"></script>
<script src="{% static "aerodromes/bower_components/datatables.net-bs/js/dataTables.bootstrap.min.js" %}"></script>
<!-- SlimScroll -->
<script src="{% static "aerodromes/bower_components/jquery-slimscroll/jquery.slimscroll.min.js" %}"></script>
<!-- FastClick -->
<script src="{% static "aerodromes/bower_components/fastclick/lib/fastclick.js" %}"></script>


<!-- page script -->
<script>
  $(function () {
      $('#example2').DataTable({
      'pageLength'  : 2,
      'paging'      : true,
      'lengthChange': true,
      'searching'   : true,
      'ordering'    : true,
      'info'        : true,
      'autoWidth'   : true,
      'lengthMenu'  : [ 1, 2, 3, 5, 10, 25, 50, 75, 100 ]
    })
  })
</script>


{% endblock %}