gestionSSA/aerodromes/urls.py
from django.urls import path
from . import views
from django.contrib import admin 


app_name='aerodromes'

urlpatterns = [
  
    path('', views.home, name='accueil'),
    path('evts/', views.pageevts, name='accueilevts'),
    path('evts/perilanimal', views.afficherperilanimal, name='perilanimal'),
    path('evts/requetesepecif', views.afficherrequetesepecif, name='requetesepecif'),
    path('evts/requetesepecif/resultatrequetespeci', views.afficherresultatrequetespeci, name='resultatrequetespeci'),
    
    path('evts/feunalaser', views.afficherfeunalaser, name='feunalaser'),
    path('psc/', views.afficherpsc, name='psc'),
    path('psc/aibd', views.afficherpscaibd, name='pscaibd'),
    path('psc/slouis', views.afficherpscslouis, name='slouis'),
    path('psc/tamb', views.afficherpsctamb, name='tamb'),
    path('psc/cap', views.afficherpsccap, name='cap'),
    path('psc/zig', views.afficherpsczig, name='zig'),
    path('pscr/', views.afficherpscr, name='pscr'),
    path('pscr/pscrcentre', views.afficherpscrcentre, name='pscrcentre'),
    path('pscr/pscrnord', views.afficherpscrnord, name='pscrnord'),
    path('pscr/pscrest', views.afficherpscrest, name='pscrest'),
    path('pscr/pscrsud', views.afficherpscrsud, name='pscrsud'),
    path('realise/', views.afficherrealise, name='realise'),
    path('aerodromesSenegal/', views.afficheraerodromesSenegal, name='aerodromesSenegal'),
    path('psc/inspectionsdepartement/', views.afficherinspectionsdepartement, name='inspectionsdepartement'),
    path('pscr/inspectionsrdepartement/', views.afficherinspectionsrdepartement, name='inspectionsrdepartement'),
    path('psc/inspectionsdepartement/aibddepart', views.afficherpscaibddepart, name='pscaibddepart'),
    path('psc/inspectionsdepartement/slouisdepart', views.afficherpscslouisdepart, name='pscslouisdepart'),
    path('psc/inspectionsdepartement/tambdepart', views.afficherpsctambdepart, name='psctambdepart'),
    path('psc/inspectionsdepartement/capdepart', views.afficherpsccapdepart, name='psccapdepart'),
    path('psc/inspectionsdepartement/zigdepart', views.afficherpsczigdepart, name='psczigdepart'),
    path('planform/', views.homeplanform, name='accueilplanform'),
    path('planning/', views.afficherplanning, name='planning'),
    path('documentation/', views.afficherdocumentation, name='documentation'),
    path('planning/formationsdepartement/', views.afficherformationsdepartement, name='formationsdepartement'),
    path('realise/dossierinspection', views.afficherdossierinspection, name='dossierinspection'),
    path('formationsrealisees/', views.afficherformationsrealisees, name='formationsrealisees'),
    path('prioriteformations/', views.afficherprioriteformations, name='prioriteformations'),
    path('listeinspecteurs/', views.afficherlisteinspecteurs, name='listeinspecteurs'),  
    
    path('formationsrealisees/dossierformation', views.afficherdossierformation, name='dossierformation'),
    path('listeinspecteurs/dossieragent', views.afficherdossierinspecteur, name='dossieragent'),
    
    path('aerodromesSenegal/dossieraerodrome', views.afficherdossieraerodrome, name='dossieraerodrome'),
    path('evts/dossierevenementsecu', views.afficherdossierevenementsecu, name='dossierevenementsecu'),
    
    
        
    path('admin/', admin.site.urls),   
]

gestionSSA/comptes/urls.py
from django.urls import path
from django.contrib.auth import views


app_name='comptes'

urlpatterns = [
  
    path('login/', views.LoginView.as_view(), name='login'),
    path('logout/', views.LogoutView.as_view(), name='logout'),
    path('password-reset/', views.PasswordResetView.as_view(), name='password_reset'),
	 path('password-reset/done/', views.PasswordResetDoneView.as_view(), name='password_reset_done'),
 	 path('reset/<uidb64>/<token>/', views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
	 path('reset/done/', views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
    path('password-change/', views.PasswordChangeView.as_view(), name='password_change'),
	 path('password-change/done/', views.PasswordChangeDoneView.as_view(), name='password_change_done'),
	 
]

gestionSSA/gestionSSA/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings



urlpatterns = [
	 path('admin/', admin.site.urls),
	 path('comptes/', include('comptes.urls')),
	 path('aerodromes/', include('aerodromes.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) 

gestionSSA/aerodromes/forms.py
from django.forms import ModelForm
from .models import Choixdepartement, Dossierinspection, Dossieraerodrome, Dossierevenementsecu, Dossierformation, Dossieragent, Evtsecurite
from django import forms



class ChoixdepartementForm(ModelForm):
    class Meta:
        model = Choixdepartement
        exclude = ['descript']
        
        
        

class DossierinspectionForm(ModelForm):
	class Meta:
		model = Dossierinspection
		exclude = ['description', 'dossierinsp', 'datedocument' ]
		

class DossieraerodromeForm(ModelForm):
	class Meta:
		model = Dossieraerodrome
		exclude = ['descriptiondossier', 'dossieraero', 'datedoc' ]
		
		

class DossierevenementsecuForm(ModelForm):
	class Meta:
		model = Dossierevenementsecu
		exclude = ['descriptiondocumentevt', 'dossierevt', 'datedocumentevt' ]
		
		
class DossierformationForm(ModelForm):
	class Meta:
		model = Dossierformation
		exclude = ['description', 'dossierformation', 'datedocument' ]
		
		
		
class DossieragentForm(ModelForm):
	class Meta:
		model = Dossieragent
		exclude = ['descriptiondocumentagent', 'dossieragent', 'datedocumentagent' ]
		
		

class EvtsecuriteForm(ModelForm):
	
	choixaero = forms.BooleanField(initial=False, required=False)
	choixdebut = forms.DateField(required=False)
	choixfin = forms.DateField(required=False)
	choixperiode = forms.BooleanField(initial=False, required=False)
	
	
	class Meta:
		model = Evtsecurite
		exclude = ['latitudeevt', 'longitudeevt', 'dateevt', 'heureevt', 'notifiantevt', 'immataeronefevt', 
		'descripinsp', 'notifevt', 'nomanimalevt', 'statutevt', 'lieuevt', 'classeevt', 'groupeanimalevt']
		
		

"""class ChoixrequeteForm(forms.Form):
	choixclassevt = forms.BooleanField(required=False)
	choixgrpanim = forms.BooleanField(required=False)
	choixaero = forms.BooleanField(required=False)
	choixdebut = forms.DateField(required=False)
	choixfin = forms.DateField(required=False)
	choixperiode = forms.BooleanField(required=False)"""
	   

   

gestionSSA/aerodromes/views.py
from django.shortcuts import render,redirect
from django.contrib.auth.decorators import login_required
from .models import Inspection, Aerodrome
import collections

from django.http import HttpResponse, Http404
from datetime import datetime, timedelta

from .models import Agentac, Formationac, DomaineInspection, Dossierinspection, Dossieraerodrome, Evtsecurite, Dossierevenementsecu, Dossierformation, Dossieragent, Document
from django.views import generic
from django.contrib.auth.decorators import login_required

from .forms import ChoixdepartementForm, DossierinspectionForm, DossieraerodromeForm, DossierevenementsecuForm, DossierformationForm, DossieragentForm, EvtsecuriteForm
from django.db.models import Q



@login_required
def home(request):
	
	aeroportinternationaux = Aerodrome.objects.filter(Q(aerointernational=True))
	aeroportnationaux = Aerodrome.objects.filter(Q(aerointernational=False))
	
	return render(request, 'aerodromes/accueil.html', {
	'aeroportinternationaux': aeroportinternationaux,
	'aeroportnationaux': aeroportnationaux,
	
	 })


@login_required
def pageevts(request):
	evenementssecurite = Evtsecurite.objects.all()
	tauxevtsPAN = 0
	tauxevtsFDG = 0
	tauxevtsMET = 0
	tauxevtsAUT = 0
	
	nbreevtsecu = Evtsecurite.objects.all().count()
	nbreevtsPAN = Evtsecurite.objects.filter(Q(typeevt='PAN')).count()
	nbreevtsFDG = Evtsecurite.objects.filter(Q(typeevt='FDG')).count()
	nbreevtsMET = Evtsecurite.objects.filter(Q(typeevt='MET')).count()
	
	if(nbreevtsecu != 0):
		tauxevtsPAN = round(100*(nbreevtsPAN/nbreevtsecu),2)
		tauxevtsFDG = round(100*(nbreevtsFDG/nbreevtsecu),2)
		tauxevtsMET = round(100*(nbreevtsMET/nbreevtsecu),2)
		tauxevtsAUT = round((100*(nbreevtsecu - nbreevtsPAN - nbreevtsFDG - nbreevtsMET)/nbreevtsecu),2)
	
	form = DossierevenementsecuForm()
	return render(request, 'aerodromes/evenementsSecurite/accueil.html', {
	'evenementssecurite': evenementssecurite,
	'form': form,
	'tauxevtsPAN': tauxevtsPAN,
	'tauxevtsFDG': tauxevtsFDG,
	'tauxevtsMET': tauxevtsMET,
	'tauxevtsAUT': tauxevtsAUT,
	
	})
    



@login_required
def afficherperilanimal(request):
    """ Exemple de page non valide au niveau HTML pour que l'exemple soit concis """
    
   
    anneecourante = datetime.today().year
         
    evtsecuanneecourante = Evtsecurite.objects.filter(Q(dateevt__year = anneecourante), Q(typeevt = 'PAN'))
    evtsecuanneepreceden = Evtsecurite.objects.filter(Q(dateevt__year = anneecourante-1), Q(typeevt = 'PAN'))
    
    nbreevtsecuanneecourante = evtsecuanneecourante.count()
    nbreevtsecuanneepreceden = evtsecuanneepreceden.count()
        
    formattedtypeevts = [format(evt.dateevt.month) for evt in evtsecuanneecourante]
    formattedtypeevtsp = [format(evt.dateevt.month) for evt in evtsecuanneepreceden]
    
    evtpanancourparmois = {x:formattedtypeevts.count(x) for x in formattedtypeevts}
    lesevtpan = list(evtpanancourparmois.keys())
    nbredevpanparmois = list(evtpanancourparmois.values())
    evtspanmoisnbre = []
    cteur = 0
    for i in lesevtpan:
    	bonformat = {}
    	bonformat['mois'] = lesevtpan[cteur]
    	bonformat['nbreevt'] = nbredevpanparmois[cteur]
    	evtspanmoisnbre.append(bonformat)
    	cteur = cteur + 1
    
    evtspanmoisnbre = sorted(evtspanmoisnbre, key = lambda i: i['mois'])
    
    evtpanancourparmoisp = {x:formattedtypeevtsp.count(x) for x in formattedtypeevtsp}
    lesevtpanp = list(evtpanancourparmoisp.keys())
    nbredevpanparmoisp = list(evtpanancourparmoisp.values())
    evtspanmoisnbrep = []
    cteur = 0
    for i in lesevtpanp:
    	bonformatp = {}
    	bonformatp['mois'] = lesevtpanp[cteur]
    	bonformatp['nbreevt'] = nbredevpanparmoisp[cteur]
    	evtspanmoisnbrep.append(bonformatp)
    	cteur = cteur + 1
    
    evtspanmoisnbrep = sorted(evtspanmoisnbrep, key = lambda i: i['mois'])
    bonnelisteevt = []
    for i in range(12):
    	bonformatbon = {}
    	bonformatbon['mois'] = i+1
    	bonformatbon['nbreevt'] = 0
    	bonnelisteevt.append(bonformatbon)
    	
    bonnelisteevtan = []
    for i in range(12):
    	bonformatbonan = {}
    	bonformatbonan['mois'] = i+1
    	bonformatbonan['nbreevt'] = 0
    	bonnelisteevtan.append(bonformatbonan)
    	
    for ev in evtspanmoisnbre:
    	for i in bonnelisteevtan:
    		if str(ev['mois']) == str(i['mois']):
    			i['nbreevt'] = ev['nbreevt']
    	
    for ev in evtspanmoisnbrep:
    	for i in bonnelisteevt:
    		if str(ev['mois']) == str(i['mois']):
    			i['nbreevt'] = ev['nbreevt']
  	              
    
    return render(request, 'aerodromes/evenementsSecurite/Perilanimalier.html',{
    
    'bonnelisteevt': bonnelisteevt,
    'bonnelisteevtan': bonnelisteevtan,
    'anneecourante': anneecourante,
    'anneeprecedente': anneecourante-1,
    'evtsecuanneecourante': evtsecuanneecourante, 
    'evtsecuanneepreceden': evtsecuanneepreceden,
    'nbreevtsecuanneepreceden': nbreevtsecuanneepreceden,
    'nbreevtsecuanneecourante': nbreevtsecuanneecourante,
    })
    



@login_required
def afficherrequetesepecif(request):
    """ Exemple de page non valide au niveau HTML pour que l'exemple soit concis """
    
    anneecourante = datetime.today().year
    evenementssecurites = Evtsecurite.objects.all()
         
    evtsecuanneecourante = Evtsecurite.objects.filter(Q(dateevt__year = anneecourante))
    evtsecuanneepreceden = Evtsecurite.objects.filter(Q(dateevt__year = anneecourante-1))
    
    nbreevtsecuanneecourante = evtsecuanneecourante.count()
    nbreevtsecuanneepreceden = evtsecuanneepreceden.count()
        
    formattedtypeevts = [format(evt.dateevt.month) for evt in evtsecuanneecourante]
    formattedtypeevtsp = [format(evt.dateevt.month) for evt in evtsecuanneepreceden]
    
    evtpanancourparmois = {x:formattedtypeevts.count(x) for x in formattedtypeevts}
    lesevtpan = list(evtpanancourparmois.keys())
    nbredevpanparmois = list(evtpanancourparmois.values())
    evtspanmoisnbre = []
    cteur = 0
    for i in lesevtpan:
    	bonformat = {}
    	bonformat['mois'] = lesevtpan[cteur]
    	bonformat['nbreevt'] = nbredevpanparmois[cteur]
    	evtspanmoisnbre.append(bonformat)
    	cteur = cteur + 1
    
    evtspanmoisnbre = sorted(evtspanmoisnbre, key = lambda i: i['mois'])
    
    evtpanancourparmoisp = {x:formattedtypeevtsp.count(x) for x in formattedtypeevtsp}
    lesevtpanp = list(evtpanancourparmoisp.keys())
    nbredevpanparmoisp = list(evtpanancourparmoisp.values())
    evtspanmoisnbrep = []
    cteur = 0
    for i in lesevtpanp:
    	bonformatp = {}
    	bonformatp['mois'] = lesevtpanp[cteur]
    	bonformatp['nbreevt'] = nbredevpanparmoisp[cteur]
    	evtspanmoisnbrep.append(bonformatp)
    	cteur = cteur + 1
    
    evtspanmoisnbrep = sorted(evtspanmoisnbrep, key = lambda i: i['mois'])
    bonnelisteevt = []
    for i in range(12):
    	bonformatbon = {}
    	bonformatbon['mois'] = i+1
    	bonformatbon['nbreevt'] = 0
    	bonnelisteevt.append(bonformatbon)
    	
    bonnelisteevtan = []
    for i in range(12):
    	bonformatbonan = {}
    	bonformatbonan['mois'] = i+1
    	bonformatbonan['nbreevt'] = 0
    	bonnelisteevtan.append(bonformatbonan)
    	
    for ev in evtspanmoisnbre:
    	for i in bonnelisteevtan:
    		if str(ev['mois']) == str(i['mois']):
    			i['nbreevt'] = ev['nbreevt']
    	
    for ev in evtspanmoisnbrep:
    	for i in bonnelisteevt:
    		if str(ev['mois']) == str(i['mois']):
    			i['nbreevt'] = ev['nbreevt']
    
   
    
    form = EvtsecuriteForm()	
    
    return render(request, 'aerodromes/evenementsSecurite/requetesepecif.html', {
    'form': form,
    
    'bonnelisteevt': bonnelisteevt,
    'bonnelisteevtan': bonnelisteevtan,
    'anneecourante': anneecourante,
    'anneeprecedente': anneecourante-1,
    'evtsecuanneecourante': evtsecuanneecourante, 
    'evtsecuanneepreceden': evtsecuanneepreceden,
    'nbreevtsecuanneepreceden': nbreevtsecuanneepreceden,
    'nbreevtsecuanneecourante': nbreevtsecuanneecourante,
    'evenementssecurites': evenementssecurites,
    
    })


@login_required
def afficherresultatrequetespeci(request):
	
	if request.method == 'POST':
		aerodevt = '--(TOUS)'
		
		choixdebut = '--'
		choixfin = '-- (à tout moment)'
		form = EvtsecuriteForm(request.POST)
		
		if form.is_valid():
			typedevt = form.cleaned_data['typeevt']
			
			choixaero = form.cleaned_data['choixaero']
			choixperiode = form.cleaned_data['choixperiode']
									
			anneecourante = datetime.today().year
			evenementssecurites = Evtsecurite.objects.filter(Q(typeevt = typedevt))
			
			evtsecuanneecourante = Evtsecurite.objects.filter(Q(dateevt__year = anneecourante), Q(typeevt = typedevt))
			evtsecuanneepreceden = Evtsecurite.objects.filter(Q(dateevt__year = anneecourante-1), Q(typeevt = typedevt))
			
			if choixaero == True:
				aerodevt = form.cleaned_data['nomaero'].nomaero
				evtsecuanneecourante = evtsecuanneecourante.filter(Q(nomaero__nomaero = aerodevt))
				evtsecuanneepreceden = evtsecuanneepreceden.filter(Q(nomaero__nomaero = aerodevt))
			if choixperiode == True:
				choixdebut = form.cleaned_data['choixdebut']
				choixfin = form.cleaned_data['choixfin']
				evenementssecurites = evenementssecurites.filter(Q(dateevt__lte = choixfin), Q(dateevt__gte = choixdebut))
			
			formattedtypeevts = [format(evt.dateevt.month) for evt in evtsecuanneecourante]
			formattedtypeevtsp = [format(evt.dateevt.month) for evt in evtsecuanneepreceden]
			evtpanancourparmois = {x:formattedtypeevts.count(x) for x in formattedtypeevts}
			lesevtpan = list(evtpanancourparmois.keys())
			nbredevpanparmois = list(evtpanancourparmois.values())
			evtspanmoisnbre = []
			cteur = 0
			for i in lesevtpan:
				bonformat = {}
				bonformat['mois'] = lesevtpan[cteur]
				bonformat['nbreevt'] = nbredevpanparmois[cteur]
				evtspanmoisnbre.append(bonformat)
				cteur = cteur + 1
				
			evtspanmoisnbre = sorted(evtspanmoisnbre, key = lambda i: i['mois'])
			evtpanancourparmoisp = {x:formattedtypeevtsp.count(x) for x in formattedtypeevtsp}

gestionSSA/aerodromes/templates/aerodromes/planformations/agentac.html
{% extends 'adminlte/base.html' %}

{% block title %}My App{% endblock %}
{% block logo_href %}{% endblock %}
{% block page_name %}AFFICHAGE AGENT{% endblock %}
{% block page_actions %}action{% endblock %}
{% block page_description %}Description{% endblock %}
{% block breadcrumbs %}
 { Breadcrumb implementation left to developers }
{% endblock %}
{% block content %}
    Just some example content
{% endblock %}
{% load static %}


<link rel="stylesheet" type="text/css" href="{% static 'planformations/style.css' %}">

<h1>Bienvenue sur le site de gestion du service SA - Ajout d'un agent


<img src="{% static "planformations/kho.JPG" %}" alt="Mon image">
<p>Date actuelle : {{date}}</p>

{% if envoiagentac %}
    <p>Votre agent a bien été enregistré !</p>
{% endif %}

</h1>

<form method="post" enctype="multipart/form-data" action=".">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Envoyer" />
</form>

gestionSSA/aerodromes/templates/aerodromes/planformations/formation.html
<h1>Bienvenue sur le site de gestion du service SA - Pour la formation:</h1>
<p>Date actuelle : {{ date }}</p>


{% if envoi %}Votre message a bien été envoyé !{% endif %}

<form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Envoyer" />
</form>

gestionSSA/aerodromes/templates/aerodromes/planformations/formationsdepartement.html
{% extends 'adminlte/base.html' %}
{% load static %}
{% block extra_head %}

 <!-- <link href="{% static "planformations/fullcalendar/core/main.css" %}" rel="stylesheet" />
 <link href="{% static "planformations/fullcalendar/daygrid/main.css" %}" rel="stylesheet" /> -->

<link href="{% static "aerodromes/fullcalendar/fullcalendar.css" %}" rel="stylesheet" />
<link href="{% static "aerodromes/bower_components/select2/dist/css/select2.min.css" %}" rel="stylesheet" />

{% endblock %}
{% block title %}ANACIM DNAA{% endblock %}
{% block logo_href %}/{% endblock %}
{% block page_name %}TABLEAU DE BORD{% endblock %}
{% block page_actions %}{% endblock %}
{% block page_description %}{% endblock %}
{% block breadcrumbs %}

{% endblock %}
{% block content_wrapper %}
   
  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
  
    <section class="content-header">
    {% if nbrechevauchements > 0 %}
       
    <div class="dropdown notifications-menu  pull-right" >
      <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              <i class="fa fa-warning text-yellow"></i> {{ nbrechevauchements }}
              <!--<span class="label label-warning">{{ nbrechevauchements }}</span>-->
            </a>
            <ul class="dropdown-menu">
              <li class="header">Vous avez {{ nbrechevauchements }} chevauchement(s):  formations impactées</li>
              
                  
                  {% for f in formationimpactees %}
                  
                  <li>
                <!-- inner menu: contains the actual data -->
                <a href="/admin">
                      <i class="fa fa-warning text-yellow"></i> 
                      {{ f.code1 }}_{{ f.matricule1 }}  -- du {{ f.debut1 }} au {{ f.fin1 }} et 
                      {{ f.code2 }}_{{ f.matricule2 }} -- du {{ f.debut2 }} au {{ f.fin2 }} 
                    </a>
                  </li>
                  {% endfor %}
                  </ul>
     
    </div>
     
     {% endif %}
      <h1>
        PLANNING DE FORMATIONS PAR DEPARTEMENT/
        <small>des Agents</small>
      </h1>
     
    </section>

    <!-- Main content -->
    <section class="content">
 
      
      <div class="row">
       <div class="col-lg-3 col-xs-4">
      
       <div class="row">
        <div class="col-lg-12 col-xs-12">
        <h5>  INSPECTEURS </h5>
               
        </div>
        
        </div>
        <div class="row">
        
        <div class="col-lg-12 col-xs-12">
         
            <div class="table-responsive mailbox-messages">
             <table class="table table-hover table-striped">
             <tbody>
         
             {% for inspect in listeinspecteurs %}
             <tr>
                  <td><b>{{ inspect.matriculebf }}-{{ inspect.prenomsagbf }} {{ inspect.nomagbf }} </b></td>
                    
             </tr>
             {% endfor %}
             
            
             </tbody>
             </table>
             </div>
              <form action="{% url 'aerodromes:formationsdepartement' %}" method="post">
    
    
               <div class="form-group">
                <label><h5>Choisir Département et valider pour afficher le planning</h5> </label>
                 {% csrf_token %}
    				  {{ form }}
    				 
               </div>    
              
              <input type="submit" value="VALIDER">
              </form>

        </div>
        
       
        </div>
        </div>
       <div class="col-lg-9 col-xs-8">
      	 <div id="calendar"></div>
       </div>
      </div>
               

    </section>
    <!-- /.content -->
  </div>
  <!-- /.content-wrapper -->    
   
    
{% endblock %}
{% block extra_foot %}
<!--<script src="{% static "planformations/fullcalendar/core/main.js" %}"></script>
<script src="{% static "planformations/fullcalendar/daygrid/main.js" %}"></script>-->

<script src="{% static "aerodromes/fullcalendar/bower_components/moment/moment.js" %}"></script>
<script src="{% static "aerodromes/fullcalendar/fullcalendar.js" %}"></script>
<script src="{% static "aerodromes/bower_components/fullcalendar/dist/locale/fr.js" %}"></script>
<script src="{% static "aerodromes/bower_components/select2/dist/js/select2.full.min.js" %}"></script>

<script type="text/javascript" >

// Code goes here
$(document).ready(function() {

/*var debutinspection = "{{ debutinsp }}",
	 fininspection = "{{ fininsp }}",
	 domaineinspection = "{{ domaineinsp }}",
	 /*inspection_bon_format
	 for (i in inspections) {
	 inspection.
	 	
	 }
	     
	 domaineinspection = domaineinspection.replace("[","")
	 domaineinspection = domaineinspection.replace("]","")
	 domaineinspection = domaineinspection.replace(/&#39;/g, "")
	 domaineinspection = domaineinspection.split(',')
	 
	 fininspection = fininspection.replace("[","")
	 fininspection = fininspection.replace("]","")
	 fininspection = fininspection.replace(/&#39;/g, "")
	 fininspection = fininspection.split(',')
	 
	 debutinspection = debutinspection.replace("[","")
	 debutinspection = debutinspection.replace("]","")
	 debutinspection = debutinspection.replace(/&#39;/g, "")
	 debutinspection = debutinspection.split(',')*/
	 
	 
	 function couleur(nomaerodrome) {
	 couleurevt = 'blue';
	 if (nomaerodrome.search(/aibd/i) >= 0) 
	 	couleurevt = 'green';
	 if (nomaerodrome.search(/louis/i) >= 0) 
	 	couleurevt = 'orange';
	  if (nomaerodrome.search(/tamba/i) >= 0) 
	 	couleurevt = 'blue';
	 if (nomaerodrome.search(/zig/i) >= 0) 
	 	couleurevt = 'red';
	 if (nomaerodrome.search(/cap/i) >= 0) 
	 	couleurevt = 'black';
	 		 
	 return couleurevt;
	 }
	 



  // page is now ready, initialize the calendar...

  var calendar = $('#calendar').fullCalendar({
    // put your options and callbacks here
    //lang  : 'fr',
    header: {
      left: 'prev,next today',
      center: 'title',
      right: 'year,month,basicWeek,basicDay'

    },
     buttonText: {
        today: "Aujourd'hui",
        year : 'Année',
        month: 'Mois',
        week : 'Semaine',
        day  : 'Jour'
      },
  
    //timezone: 'local',
    height: "auto",
    selectable: true,
    dragabble: true,
    defaultView: 'year',
    yearColumns: 3,

    durationEditable: true,
    bootstrap: false,

    events: [
    {% for i in listeformations %}
     
    {  
    
      title: '{{ i.matriculebf }}' + '-' + '{{ i.nomformbf }}',         
      start:  '{{ i.debutformbf }}',
      end:  '{{ i.finformbf }}',
      allDay: true,
      description: '{{ i.lieuformbf }}',
      
      //editable: true,
      
      eventDurationEditable: true,
      color : couleur('{{ i.nomformbf }}'),
    }, 
   
   
    {% endfor %}
    ],
    /*select: function(start, end, allDay) {
      var title = prompt('Libellé de la mission:');
      if (title) {
        var event = {
          title: title,
          start: start.clone(),
          end: end.clone(),
          allDay: true,
          editable: true,
          eventDurationEditable: true,
          eventStartEditable: true,
          color: 'red',
        };

        calendar.fullCalendar('renderEvent', event, true);
      }
    },*/
    
    eventRender: function(event, element) {
    $(element).tooltip({title: event.title +  " du " + event.start.date() + " au " + event.end.date() + " à " + event.description});
}
    
  });
});

 $(function () {
 //Enable check and uncheck all functionality
    $('.checkbox-toggle').click(function () {
      var clicks = $(this).data('clicks')
      if (clicks) {
        //Uncheck all checkboxes
        $('.mailbox-messages input[type=\'checkbox\']').prop('checked', false)
        
      
      } else {
        //Check all checkboxes
        $('.mailbox-messages input[type=\'checkbox\']').prop('checked', true)
       //document.getElementById("sli").checked = false
      }
      $(this).data('clicks', !clicks)
    })
})
</script>

{% endblock %}